name: Deployment

concurrency: production

on:
  push:
    branches:
      - main
      
permissions:
  contents: read

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          host=HOST_NAME
          hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
          ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts
      - run: echo "$HOME/Customer_Intervention_React_Application/build/*" >> $GITHUB_PATH
      - run: scp -r $GITHUB_PATH ubuntu@138.197.140.201:/var/www/mobile.monichan.com/html
