name: learn-github-actions
on:
  push:
    branches: [ "main" ]
    
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    

    steps:
      - run: echo "$HOME/Customer_Intervention_React_Application/build/*" >> $GITHUB_PATH:
      - run: scp -r $GITHUB_PATH ubuntu@138.197.140.201:/var/www/mobile.monichan.com/html
